# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message

# You can manually trigger a dependabot run in the "Insights -> Dependency Graph -> Dependabot" section of the repository.

# See also:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates
# Available commands: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands
# Debugging/testing: https://github.com/dependabot/cli

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "nuget"
    directory: "/src/vs-bicep"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/src/vscode-bicep"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      # we're deliberately taking a dependency on an older version of vscode for back-compatibility
      - dependency-name: "@types/vscode"
        versions:
        - ">1.52.0"
  - package-ecosystem: "npm"
    directory: "/src/playground"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/src/Bicep.Cli.E2eTests"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/src/Bicep.MSBuild.E2eTests"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/src/textmate"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/src/highlightjs"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/src/monarch"
    schedule:
      interval: "weekly"
      day: "sunday"
