name: PR Compliance

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-for-docs-label:
    name: Check for Docs label
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'ðŸ“˜ Docs Needed') || contains(github.event.pull_request.labels.*.name, 'ðŸ“˜ Docs Not Needed') || contains(github.event.pull_request.labels.*.name, 'dependencies')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Docs label is missing
        run: |
          echo 'All PRs must either have the `ðŸ“˜ Docs Needed` or `ðŸ“˜ Docs Not Needed` label applied' >> $GITHUB_STEP_SUMMARY
          exit 1
