name: Update Baselines
# This action can be run on-demand against a branch.
# It attempts to update the baseline files, and commits and pushes changes if there are any.

on:
  workflow_dispatch:

jobs:
  main:
    name: Update Baselines
    runs-on: ubuntu-latest

    env:
      # don't print dotnet logo
      DOTNET_NOLOGO: true

      # disable telemetry (reduces dotnet tool output in logs)
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.8.2
      
      - name: Test
        continue-on-error: true
        run: dotnet test --filter "TestCategory=Baseline" -- 'TestRunParameters.Parameter(name="SetBaseLine", value="true")'
      
      - name: Commit baselines
        run: |
          git config --global user.email "bicep@noreply.github.com"
          git config --global user.name "Bicep Automation"

          git add .

          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update test baselines"
            git push
          fi